### PR TITLE
master-bl-42

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-29540

Please backport this to 7.0.x.

See corresponding test [here](https://github.com/alee8888/liferay-portal/pull/421).

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:stop

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
SF for KSuetani:
1. Split out the testcase into two tests.
2. Created a SignInNavigator macro that navigates to Create Account in the Sign In portlet.

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/46185
https://github.com/brianchandotcom/liferay-portal/pull/46186

**Pull request closed without merging**
