### PR TITLE
master-qa-21046

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-21046

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
Aborted due to known start-up issue caused by https://github.com/liferay/liferay-portal/commit/d992d839572c70e1e93be6c97b1566069941a69f

After this <a href="https://github.com/brianchandotcom/liferay-portal/pull/34330">pull</a> is merged we can re-run this particular pull request.

Sorry for the inconvenience.

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
Closing this PR. Will resubmit when tests have been fixed.

**Pull request closed without merging**
