### PR TITLE
master-qa-26402-1

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-26402

See PR tester results [here](https://github.com/xbrianlee/liferay-portal-ee/pull/7).
See PR with corresponding build script changes [here](https://github.com/alee8888/liferay-portal/pull/272).

**Test failure will be fixed once #272 is merged.**

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/42024
https://github.com/brianchandotcom/liferay-portal/pull/42025

**Pull request closed without merging**
