### PR TITLE
LRQA-35988 Disable HTTP for Elasticsearch

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
ci:stop

**Comment by alee8888** [comment]
ci:retest

**Comment by alee8888** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by alee8888** [comment]
ci:retest

**Comment by alee8888** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianchiu** [comment]
There are definitely some consistent failures.

Poshi failures:
ClusteringCE#AddAndDeleteBlogEntriesOnSeparateNodes

The http error showed up in the lpkg release batch (in the most recent run). The lpkg batch builds the lpkg's on its own, so it wouldn't have the this particular change, right?

@alee8888

**Pull request closed without merging**
