### PR TITLE
master-qa-24984

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-24901
https://issues.liferay.com/browse/LRQA-24968
https://issues.liferay.com/browse/LRQA-24984

### CODE REVIEW

**Comment by xbrianlee** [comment]
This pull is failing b/c the Elasticsearch clustering smoke test depends on the changes made in #223.

**Comment by xbrianlee** [comment]
brianchandotcom#39973 has been merged.

ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/40078. [See changes here.](https://github.com/alee8888/liferay-portal/compare/470fa1c~1...470fa1c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
SF for BLee.
1. I combined both Elasticsearch.testcase and ElasticsearchEE.testcase into one file and moved it into coreinfrastructureee.

**Pull request closed without merging**
