### PR TITLE
master-qa-25539

### PR DESCRIPTION
**Pull request by xbrianlee**
**IMPORTANT:** Do not push in these changes until after release.

https://issues.liferay.com/browse/LRQA-25539

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:stop

**Comment by brianwulbern** [comment]
@alee8888 I think this one can go in now, yes?

**Comment by brianwulbern** [comment]
ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
Pull request submitted to https://github.com/topolik/liferay-portal/pull/357. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
Pull request submitted to https://github.com/topolik/liferay-portal/pull/364. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
