### PR TITLE
master-qa-21416

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-21416

See accompanying  Elasticsearch clustering smoke test at #230.

### CODE REVIEW

**Comment by xbrianlee** [comment]
Split my commits.

ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by xbrianlee** [comment]
Abstracted plugin urls from the plugin install steps into properties.

ci:retest

**Comment by alee8888** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39973. [See changes here.](https://github.com/alee8888/liferay-portal/compare/2e1a549~1...2e1a549) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
SF for BLee.
1. Since we bundle those Elasticsearch plugins in source, we should just copy instead of downloading them each time the test is run.
2. In the prepare-elasticsearch macrodef, to keeps things consistent, I adding a conditional for Unix and then Windows.
3. For the stop-elasticsearch target, I removed "<" because that is not allowed as an argument for Ant.

**Pull request closed without merging**
