### PR TITLE
master-qa-21621

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-21621
https://issues.liferay.com/browse/LRQA-21622
https://issues.liferay.com/browse/LRQA-21623
https://issues.liferay.com/browse/LRQA-21647

### CODE REVIEW

**Comment by xbrianlee** [comment]
Updated PR with the other two tests.

ci:retest

**Comment by xbrianlee** [comment]
Updated PR with the last test.

ci:retest

**Comment by alee8888** [comment]
SF for BLee

1. Check the changes you made to search.macro on d2dd098. WCM has a test where localizationIDName is still being used for a passing test (CategoriesUsecase#AddCategorywithLocalization). Please make sure to double check before making changes to existing testcases/macros/paths. 
2. Update testcase names to include "scope"
```javascript
From: SearchTwiceThisSite
To: SearchTwiceScopeThisSite

From: SearchTwiceEverything
To: SearchTwiceScopeEverything

From: SearchTwiceLetUserChoose
To: SearchTwiceScopeLetUserChoose
```
3. Your changes to search.path in 408e310 affects other macros.
4. Make your changes to check/uncheck display facets for a particular facet more modular (00e364f  ). Update conditional
```javascript
From: <equals arg1="${uncheckDisplayFacet}" arg2="Sites" />
To: <isset var="uncheckDisplayFacet" />
```

**Comment by xbrianlee** [comment]
ci:retest

**Comment by alee8888** [comment]
No test changes needed :)

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/alee8888/liferay-portal/pull/148

**Pull request closed without merging**
