### PR TITLE
LPS-76549 Convert UserPasswordFormNavigatorEntry.java to a ScreenNavigationEntry

### PR DESCRIPTION
**Pull request by pei-jung**
Migrated the password section to Preferences tab

screen shot 2018-01-02 at 3 12 32 pm

/cc @drewbrokke

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pei-jung** [comment]
Rebased and updated branch

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pei-jung** [comment]
Resent as https://github.com/alee8888/liferay-portal/pull/524.

**Pull request closed without merging**
