### PR TITLE
master-bw-10

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-27028

@alee8888 This test fix included some relatively major surgery to `Role#editPermissionCmdCP`

@Sharryxue noticed that if the desired element is displaying *near* one that was previously used, then this `<if>` block gets skipped when it shouldn't (https://github.com/brianwulbern/liferay-portal/pull/10/commits/715f425720e1e32a33fe6093f423fd2d7cad4db3#diff-83b72a158c0735a0b5477414710abdabL585) - so her solution is to always search, which I thought was OK.

She also noticed that 2nd/3rd/4th... Permissions in for-loop succession weren't getting saved, so moved the saving inside the for-loop (https://github.com/brianwulbern/liferay-portal/pull/10/commits/715f425720e1e32a33fe6093f423fd2d7cad4db3#diff-83b72a158c0735a0b5477414710abdabR629).

I wanted to have you see these changes before sending to BChan.  Can you PR to him if it looks good?  Thanks!

**Please backport to 7.0.x.  Thanks!**

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianwulbern** [comment]
@alee8888 I think what we can do, instead, is not make any changes to the Role.macro file, but instead make all the changes in the testcase.  What I'm thinking is to use `Role#definePermissionsCP` twice, once for each permission locator, and just include re-navigation to Roles in the middle.

The reason I don't think we can combine defining both permissions into one `Role#definePermissionsCP` call is that the `<for>` loop iterates through each permission locator before saving the definition - but the beginning of the loop looks for the locator on the page and will re-search if it doesn't see it, and the problem, there, is that `RolesPermissions#CONTROL_PANEL_USERS_ROLES_GENERAL_PERMISSIONS_ACCESS_IN_CONTROL_PANEL_CHECKBOX` and `RolesPermissions#CONTROL_PANEL_SITES_SITES_GENERAL_PERMISSIONS_ACCESS_IN_CONTROL_PANEL_CHECKBOX` share an identical locator.  So it loops through the `<for>` block twice, the second time, not checking the box it already thinks is checked.

**Comment by alee8888** [comment]
Closing as Sharry is going to make changes and resend to Brian Wulbern.

**Comment by brianwulbern** [comment]
Thanks, @alee8888!

**Pull request closed without merging**
