### PR TITLE
LPS-75941 Automatically deploy the user data demo creator module

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-75941](https://issues.liferay.com/browse/LPS-75941).<br><br>Hey Albert, can you or a teammate update any Poshi tests that need it because of these changes? Let me know if you have any questions.  Thanks!<br><br>/cc @pei-jung

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:retest

**Comment by pei-jung** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
@alee8888 any word on this pull?

**Comment by alee8888** [comment]
@drewbrokke Hey Drew, sorry JP and Andrew are working on this.

**Comment by drewbrokke** [comment]
Hey @alee8888 is there any update on this ticket?

**Comment by xbrianlee** [comment]
ci:close

Running acceptance tests with fixes in https://github.com/xbrianlee/liferay-portal/pull/191. Track [LRQA-37752](https://issues.liferay.com/browse/LRQA-37752) for progress.

**Pull request closed without merging**
