### PR TITLE
master-qa-22866

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-22866

This PR fixes the tests that were broken by changes made in alee8888#175.

### CODE REVIEW

**Comment by xbrianlee** [comment]
Looking into these failures.

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
Unrelated test failures.

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
No test changes needed :)

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/37155

**Pull request closed without merging**
