### PR TITLE
LRQA-36771 | master

### PR DESCRIPTION
**Pull request by john-fernandez**
https://issues.liferay.com/browse/LRQA-36771

### CODE REVIEW

**Comment by john-fernandez** [comment]
ci:test

**Comment by alee8888** [comment]
ci:reopen

**Comment by john-fernandez** [comment]
https://github.com/john-fernandez/liferay-portal/pull/32

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
Pull request submitted to https://github.com/kiyoshilee/liferay-portal/pull/102. [See changes here.](https://github.com/alee8888/liferay-portal/compare/aa9c2044f0d3~1...aa9c2044f0d3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
