### PR TITLE
LPS-66403

### PR DESCRIPTION
**Pull request by natecavanaugh**
Heya Albert,
Pei-Jung asked me to forward this to you before it goes it.
Can you update any tests needed and send to bchan?

Thanks!

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
Tests will be fixed in https://issues.liferay.com/browse/LRQA-25994

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/40936

**Pull request closed without merging**
