### PR TITLE
LPS-64486

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-64486

Plugins PR submitted here:
alee8888/liferay-plugins#3

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by xbrianlee** [comment]
Split up commit into smaller, more specific ones.

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
SF for BLee:
1. Split out app.server.tcserver.tomcat.version=8.0.26.B.RELEASE into its own commit and make sure commit message is descriptive in explaining why this needs to be added.

**Comment by xbrianlee** [comment]
Split app.server.tcserver.tomcat.version into it's own commit.

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
No test changes needed :)

@xbrianlee this isn't a SF but something to keep in mind. Because we are running tc Server 3.1.2 on Tomcat 8, MaxPermSize is no longer applicable due to JDK 8. I updated it to MaxMetaspaceSize.

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/38707

**Pull request closed without merging**
