### PR TITLE
LPS-66238 As a users admin I would like to see a unified list, pagination and actions for organizations and users

### PR DESCRIPTION
**Pull request by pei-jung**
https://issues.liferay.com/browse/LPS-66238

Hey Albert,

This PR contains changes to the UI of the organization view. Please update the tests that might be affected by these changes. Let me know if you have any questions.

Thanks!

/cc @jorgeferrer @drewbrokke @jonmak08

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:retest

**Comment by pei-jung** [comment]
ci:stop

**Comment by pei-jung** [comment]
ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
ci:retest

**Comment by alee8888** [comment]
Resent here: https://github.com/alee8888/liferay-portal/pull/375

**Pull request closed without merging**
