### PR TITLE
LRQA-33319 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Hey Albert, these are the macros for defining role permissions through the API. Looking for feedback on the macro naming if you have any. I converted one of your tests and one of my tests. I also wrote documentation on how to do the conversions because it requires the test writer to look at the database to confirm the variable values. The documentation will be sent after this is merged. Please assign the ticket back to me when you are done.

https://issues.liferay.com/browse/LRQA-33319

### CODE REVIEW

**Comment by vicnate5** [comment]
CC @brianchiu

**Comment by brianchiu** [comment]
@vicnate5 Nice!

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
Pushed to BChan (master).
https://github.com/brianchandotcom/liferay-portal/pull/49983

Pushed to GRen (ee-7.0.x).
https://github.com/ginsonren/liferay-portal-ee/pull/222

**Pull request closed without merging**
