### PR TITLE
master-qa-19859

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-19859

### CODE REVIEW

**Comment by xbrianlee** [comment]
I approved my change in Message.path (be96a0fdb592164e3743c6077052340b26e746ac) with @sharonchoi.

**Comment by xbrianlee** [comment]
ci:retest

**Comment by alee8888** [comment]
No test changes needed :)

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/32906

**Pull request closed without merging**
