### PR TITLE
master-LPS-89557

### PR DESCRIPTION
**Pull request by Sharryxue**
Hello @alee8888 ,
I've updated one macro that might be affected, I've run the case on local, and it can be passed.

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
force updated the branch to resolve the SF issue

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/1705. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
