### PR TITLE
master-qa-23882

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-23882
https://issues.liferay.com/browse/LRQA-24153
https://issues.liferay.com/browse/LRQA-22722

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
Unrelated test failures. Also `Forms#ConfigureDataProviderWithSelectField` test failure on previous run was a fluke.

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
No test changes needed :)

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/38758

**Pull request closed without merging**
