### PR TITLE
master-qa-24422

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-24422
https://issues.liferay.com/browse/LRQA-22741
https://issues.liferay.com/browse/LRQA-24403
https://issues.liferay.com/browse/LRQA-24407
https://issues.liferay.com/browse/LRQA-24406
https://issues.liferay.com/browse/LRQA-24420

### CODE REVIEW

**Comment by xbrianlee** [comment]
Fixing rebase issue.

**Comment by xbrianlee** [comment]
ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
No test changes needed :)

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/38874

**Pull request closed without merging**
