### PR TITLE
master-bl-13

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-21568
https://issues.liferay.com/browse/LRQA-22495

### CODE REVIEW

**Comment by xbrianlee** [comment]
Unrelated failures.

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
No test changes needed :)

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/37121

**Pull request closed without merging**
