### PR TITLE
LPS-75941 | master - User Data Demo Creator Module

### PR DESCRIPTION
**Pull request by joshchong**
This includes the test fixes associated with the automatic deploy of the user data demo creator module

https://issues.liferay.com/browse/LRQA-37752
https://issues.liferay.com/browse/LPS-75941

### CODE REVIEW

**Comment by joshchong** [comment]
Acceptance tests have passed here: john-fernandez#21

**Comment by joshchong** [comment]
ci:retest

**Comment by joshchong** [comment]
ci:reopen

**Comment by joshchong** [comment]
ci:retest

**Comment by joshchong** [comment]
ci:stop

**Comment by joshchong** [comment]
ci:stop

**Comment by joshchong** [comment]
ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by xbrianlee** [comment]
ci:close

**Pull request closed without merging**
