### PR TITLE
master-qa-22487

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-22487
https://issues.liferay.com/browse/LRQA-22711
https://issues.liferay.com/browse/LRQA-22715

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
No test changes needed :)

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/37000

**Pull request closed without merging**
