### PR TITLE
master-qa-49249

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-49249

Hello @alee8888 ,
Here is the new test case you've requested in email for LPS-95340, I'm not sure if it was supposed to sending the pull to you. If it should be someone else, please feel free to close the pull and I'll resending the pull.

**NOTE:** This is only for master, no need to sending to 7.1.x since AP portlet cannot be added to content page on 7.1.x

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73700. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Sharryxue** [comment]
ci:close

**Pull request closed without merging**
