### PR TITLE
master-qa-27777

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-26892
https://issues.liferay.com/browse/LRQA-27777
https://issues.liferay.com/browse/LRQA-27782
https://issues.liferay.com/browse/LRQA-27786
https://issues.liferay.com/browse/LRQA-27787

@alee8888 Here are all the My Account > Organization tests.  **Please backport to 7.0.x**  Thanks!

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/44109
https://github.com/brianchandotcom/liferay-portal/pull/44110

**Pull request closed without merging**
