### PR TITLE
master-qa-21046

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-21046

### CODE REVIEW

**Comment by xbrianlee** [comment]
Adding in changes to fix failing integration tests

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:retest

**Comment by xbrianlee** [comment]
5th time's a charm
ci:retest

**Comment by alee8888** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by alee8888** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by alee8888** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by alee8888** [comment]
ci:retest

**Comment by xbrianlee** [comment]
Closing this pull. Will resend.

**Pull request closed without merging**
