### PR TITLE
LRQA-35981 | Master

### PR DESCRIPTION
**Pull request by joshchong**
https://issues.liferay.com/browse/LRQA-35981

### CODE REVIEW

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by joshchong** [comment]
I rebased my commits and made changes to the test names to be more descriptive.

**Comment by joshchong** [comment]
ci:retest

**Comment by joshchong** [comment]
Resent here to correct SF issues:
#501

**Pull request closed without merging**
