### PR TITLE
LPS-79656 Do not show custom fields section if there are none visible for the User class

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-79656](https://issues.liferay.com/browse/LPS-79656).<br><br>/cc @pei-jung

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
Hey @alee8888 can you please verify that this does not break any functional tests?  Thanks!

**Comment by alee8888** [comment]
ci:test

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61493. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
