### PR TITLE
master-qa-20419

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-20419

### CODE REVIEW

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
SF for BLee.
1. Can you please rename the macro loginUserFailPG to loginUserFailWithClusteringPG? This is so another test engineer won't mistaken this macro as a general login user fail macro and the error message we assert is pretty specific.
2. For the clustering smoke testcase, add assertions to make sure clustering startup logging isn't present in the console.

**Comment by xbrianlee** [comment]
I renamed the loginUserFailPG macro and added an assert for the usual clustering message on EE.

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
@xbrianlee 
1.  I renamed Clustering.testcase to ClusteringEE.testcase and moved it into coreinfrastructureee

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/39268

**Pull request closed without merging**
