### PR TITLE
LPS-75377 Fix semantic versioning issues

### PR DESCRIPTION
**Pull request by JorgeFerrer**
Resending after fixing source formatting and semantic versioning issues

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:test

**Comment by JorgeFerrer** [comment]
ci:reopen

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by xbrianlee** [comment]
Functional test fixes sent to https://github.com/JorgeFerrer/liferay-portal/pull/841

**Pull request closed without merging**
