### PR TITLE
master-qa-26165

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-26165

@alee8888 
Not sure the best testcase file to add this to.  This test was added on ee-6.2.x/ee-6.2.10, but needed some modification to work on master.

Please review and send to BChan (or first to another comp lead) with any changes you see fit - the test is in a Collab test file, but the operative functionality in question pertains to Permissions, so it's more of a "Usecase" test

**Please backport to 7.0.x**.

### CODE REVIEW

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
@brianwulbern 
1. Updated the testcase name
From
SearchFolderDocumentNoPermission
To
viewSearchResultsForChildObjectRespectsParentFolderPermissions
2. Instead of using Search#searchNoPG, I updated it to use Search#searchPG and then Search#viewSearchNoPG. In the future, I would like to deprecate searchNoPG because that macro does too many things.

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/42617
https://github.com/brianchandotcom/liferay-portal/pull/42618

**Comment by brianwulbern** [comment]
Nice.  I'll look for ways to deprecate Search#searchNoPG.  Thanks, Albert!

**Pull request closed without merging**
