### PR TITLE
master-qa-25023

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-25023

cc: @drewbrokke

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39735. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
