### PR TITLE
LRQA-26699 TCServer Upgrade Tests

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-26699
- This is just to see if it works or not, and can be used to debug any issues.

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by ksuetani** [comment]
ci:retest

**Pull request closed without merging**
