### PR TITLE
master-qa-20494-1

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-20494

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:retest

**Comment by alee8888** [comment]
ci:retest

**Comment by alee8888** [comment]
SF for BLee.
1. Remember to run ant format-source

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33672

**Pull request closed without merging**
