### PR TITLE
master-qa-21326

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-21326

### CODE REVIEW

**Comment by austinchiang** [comment]
@anthony-chu this change should not affect the Content Targeting tests that use the affected locator.

**Comment by anthony-chu** [comment]
@austinchiang :+1:  sounds good! thanks for checking!

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/41558

**Pull request closed without merging**
