### PR TITLE
master-bl-17

### PR DESCRIPTION
**Pull request by xbrianlee**
This PR combines work from the following tickets:
https://issues.liferay.com/browse/LRQA-22502
https://issues.liferay.com/browse/LRQA-23077

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
No test changes needed :)

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/37467

**Pull request closed without merging**
