### PR TITLE
LPS-116875 [UI] Manually add an Account Entry to an Account Group

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-116875](https://issues.liferay.com/browse/LPS-116875).

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Hello @drewbrokke 
It's probably relates failure, would you please take a look into it when you get a chance? Thanks in advance. [Jenkins console](https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/285589/testReport/com.liferay.account.rest.resource.v1_0.test/AccountResourceTest/testGetAccountsPage/)
/cc @alee8888 
```
Error Message
java.lang.IllegalArgumentException: Unsupported field name actions
	at com.liferay.account.rest.client.problem.Problem$ProblemJSONParser.setField(Problem.java:176)
	at com.liferay.account.rest.client.problem.Problem$ProblemJSONParser.setField(Problem.java:138)
	at com.liferay.account.rest.client.json.BaseJSONParser.parseToDTO(BaseJSONParser.java:90)
	at com.liferay.account.rest.client.problem.Problem.toDTO(Problem.java:33)
	at com.liferay.account.rest.client.resource.v1_0.AccountResource$AccountResourceImpl.getAccountsPage(AccountResource.java:181)
	at com.liferay.account.rest.resource.v1_0.test.BaseAccountResourceTestCase.testGetAccountsPage(BaseAccountResourceTestCase.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$2.evaluate(TestExecutorRunnable.java:234)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
```

**Comment by drewbrokke** [comment]
Thanks @Sharryxue. Thankfully this pull is not intended to be sent to upstream. We'll keep this failure in mind when we do send the final changes.

**Pull request closed without merging**
