### PR TITLE
master-bl-11

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-22679
https://issues.liferay.com/browse/LRQA-22500
https://issues.liferay.com/browse/LRQA-21328
https://issues.liferay.com/browse/LRQA-22449
https://issues.liferay.com/browse/LRQA-22005

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
SF for AChiang
1. Removed extra iframe select.

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/37136

**Pull request closed without merging**
