### PR TITLE
LRQA-35566 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-35566

Please backport!

### CODE REVIEW

**Comment by alee8888** [comment]
ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
SF for JChong
1. Consolidate navigation from PasswordPolicies.macro and MyAccount.macro into Navigation macros.
2. Rename testcase name "ViewChangeableAndChangeRequired" to be more descriptive.

**Comment by joshchong** [comment]
Resent here:
 alee8888#496

**Pull request closed without merging**
