### PR TITLE
LPS-61505 Show one single portlet name. If title is null, show displayName otherwise portletName

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by alee8888** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Hey Albert, 

Since this error does not really seam related to this pull, could you forward it to Brian?

**Comment by alee8888** [comment]
@JorgeFerrer Can you please move the status of LPS-61514 to code review? I do not know have sufficient privileges to move the workflow of story tickets. Also I did a short exploratory testing and filed LPS-61567. Thanks!

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33690

**Pull request closed without merging**
