### PR TITLE
master-bl-15

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-22748

Note: I left the organization navigation macros (12d997459d4a036d288c4366c23e43dc0d546768) even though we're not using them now. I figure they could be useful for future tests.

### CODE REVIEW

**Comment by xbrianlee** [comment]
Unrelated failures.

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
No test changes needed :)

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/37289

**Pull request closed without merging**
