### PR TITLE
master-bl-16

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-22904

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
Looking into the consistent XssUsecase#ViewGoogleAnalyticsIDNoXSS failure.

**Comment by xbrianlee** [comment]
Added step to slow ViewControlPanelNoXSS test down enough for it to finish loading site admin page.

ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
ci:retest

**Comment by alee8888** [comment]
No test changes needed :)

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/37721

**Pull request closed without merging**
