### PR TITLE
LPS-69647 Assign Organization Roles popup has no padding

### PR DESCRIPTION
**Pull request by pei-jung**
Hey @alee8888,

Can you check and update the functional tests if needed? Please forward it to Brian after you're done. Thanks!

/cc @drewbrokke @jorgeferrer

### CODE REVIEW

**Comment by ksuetani** [comment]
ci:retest

**Comment by ksuetani** [comment]
ci:reopen

**Comment by pei-jung** [comment]
ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45703. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
