### PR TITLE
LRQA-X Default config for Weblogic to avoid Google JS Compressor warning output

### PR DESCRIPTION
**Pull request by dantewang**
@alee8888 @tinatian

Instead of adding filter, I added some WLST commands to `unzip-weblogic` to raise the logging level of `com.google.javascript.jscomp`. This results in the below part of configuration in the `<server>` node in  `/path/to/wls/domains/liferay/config/config.xml` after running `unzip-weblogic`.

```
    <log>
      <name>AdminServer</name>
      <platform-logger-levels>com.google.javascript.jscomp=SEVERE</platform-logger-levels>
    </log>
```

Does this look good to you?

References:
http://www.dba-oracle.com/t_weblogic_domain_log_files.htm
https://docs.oracle.com/middleware/1221/wls/WLLOG/logging_services.htm#WLLOG214

### CODE REVIEW

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by tinatian** [comment]
@dantewang The fix is hacky and it should be a temp fix if we fix it in this way. Could you please try to find a better way to fix it?
Maybe you can compare how other type of app server config log level and how weblogic works, hope we can figure out a better solution.

Thanks.
Tina.

**Comment by dantewang** [comment]
@tinatian 

The logger that `PhaseOptimizer` obtained in Tomcat has no handler in the logger hierarchy. However, in Weblogic, there are 2 handlers in the root logger in the logger hierarchy: one is `java.util.logging.ConsoleHandler`, the other is Weblogic's `ServerLoggingHandler`. The actual logging levels on both sides are `INFO`.

So the behavior in Tomcat has nothing to do with logging level config -- it just doesn't have handler to print the log out.

The Weblogic doc provides the approach to config handlers/logging level using logging.properties which can be passed to the JVM as a startup argument (the standard JVM way).

However, it also [recommends](https://docs.oracle.com/cd/E21764_01/web.1111/e13739/logging_services.htm#WLLOG202) to change logger related configs using the `LogMBean` (either via the web console or via WLST) (the standard Weblogic way).

If using WLST is acceptable, I can try to find some cleaner ways for the script.

**Comment by alee8888** [comment]
@dantewang 
Yes, please use WLST if we can and thank you for looking into this!

**Comment by dantewang** [comment]
Update see https://github.com/alee8888/liferay-portal/pull/607

**Pull request closed without merging**
