### PR TITLE
master-qa-20728

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-20728
https://issues.liferay.com/browse/LRQA-20736

### CODE REVIEW

**Comment by xbrianlee** [comment]
Unrelated test failure.

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
No test changes needed :)

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/36738

**Pull request closed without merging**
