### PR TITLE
master-qa-21361

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-21361

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by pei-jung** [comment]
Hi guys,

what's the status of this pull?

**Comment by xbrianlee** [comment]
Hey Pei, sorry for the delay. Looks like our tests were getting aborted last week.

ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
Added a check for lockout checkbox.

ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by xbrianlee** [comment]
ci:retest

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/35065

**Pull request closed without merging**
