### PR TITLE
LRQA-37037 | master

### PR DESCRIPTION
**Pull request by andrewlam78**
https://issues.liferay.com/browse/LRQA-37037

### CODE REVIEW

**Comment by andrewlam78** [comment]
ci:test

**Comment by alee8888** [comment]
ci:stop

**Comment by andrewlam78** [comment]
https://github.com/andrewlam78/liferay-portal/pull/3

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/55385

**Pull request closed without merging**
