### PR TITLE
LPS-66239

### PR DESCRIPTION
**Pull request by natecavanaugh**
Heya Albert,
Can you review this pull from Pei-Jung and update any tests needed?

Thanks!

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
New PR will be sent in https://issues.liferay.com/browse/LRQA-26023

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/40937

**Pull request closed without merging**
