### PR TITLE
LPS-64652 Remove the ability to configure the database through the setup wizard

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
Hey @alee8888,

   For the ticket LPS-64652, we have decide remove the support for the change of the DB settings in the Setup Wizard.

   Can you help with the test that are failing? 

Thanks in advance!!!

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by alee8888** [comment]
@cgoncas I will continue the test fixes tomorrow. Thanks again!

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Pull request closed without merging**
