### PR TITLE
LPS-66237

### PR DESCRIPTION
**Pull request by natecavanaugh**
Heya Albert,
Pei-Jung asked me to forward this to you before it goes it.
Can you update any tests needed and send to bchan?

Thanks!

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:retest

**Comment by alee8888** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
Tests will be fixed in https://issues.liferay.com/browse/LRQA-25979

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by austinchiang** [comment]
Pushed to ALee: https://github.com/alee8888/liferay-portal/pull/245

**Pull request closed without merging**
