### PR TITLE
master-qa-23878

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-23878

### CODE REVIEW

**Comment by xbrianlee** [comment]
Forgot to SF. Updated my commits.

**Comment by alee8888** [comment]
Pending as I need to check with Shuyang to see if base functional cluster tests should be run using simple File System Store or DB Store.

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
No test changes needed :)

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/38935

**Pull request closed without merging**
