### PR TITLE
master-qa-20177

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-20177

### CODE REVIEW

**Comment by xbrianlee** [comment]
Need to resubmit with Drew's changes.

**Comment by xbrianlee** [comment]
ci:retest

**Comment by alee8888** [comment]
ci:retest

**Comment by alee8888** [comment]
No test changes needed :)

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33325

**Pull request closed without merging**
