### PR TITLE
LRQA-35662 | master

### PR DESCRIPTION
**Pull request by joshchong**
https://issues.liferay.com/browse/LRQA-35662

### CODE REVIEW

**Comment by joshchong** [comment]
ci:open ci:retest

**Comment by joshchong** [comment]
ci:reopen ci:retest

**Comment by joshchong** [comment]
ci:retest

**Comment by joshchong** [comment]
ci:reopen

**Comment by joshchong** [comment]
ci:retest

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
SF for JChong.
1. Please try not use function calls in testcases. Try to consolidate into smaller macros.

**Pull request closed without merging**
