### PR TITLE
LPS-76550 Convert UserPersonalSiteFormNavigatorEntry.java to a ScreenNavigationEntry

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-76550](https://issues.liferay.com/browse/LPS-76550).

Moves "Personal Site" to `General > Profile and Private Area`

screen shot 2018-01-09 at 5 02 06 pm

/cc @pei-jung

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by alee8888** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/54517.

**Pull request closed without merging**
