### PR TITLE
LPS-61318 Improve the user experience when using Portal Settings by applying Lexicon mockups

### PR DESCRIPTION
**Pull request by JorgeFerrer**
Hey Albert, this is a simple pull but it seems there is at least one POSHI test that breaks due to the changes in markup. Could you take a look at it?

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
closing temporarily. Waiting for @ealonso to confirm whether this is actually caused by a bug.

**Comment by JorgeFerrer** [comment]
Reopening once it's been confirmed that this is not caused by the bug identified by @ealonso 

Alberto, please take a look at the failing test and forward the pull to Brian. Please let me know if you have any question.

**Comment by anthony-chu** [comment]
New pull request with frontend fixes sent here: #81.

**Comment by alee8888** [comment]
@JorgeFerrer @anthony-chu @evannagayama
Hi Jorge, Anthony from the WCM QA team is taking a look at this as test case is WCM specific. He will be submitting the test fix soon. Thank you!

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33417

**Pull request closed without merging**
