### PR TITLE
TEST LPS-79566 | master

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LPS-79566

### CODE REVIEW

**Comment by jpince** [comment]
ci:test

**Comment by jpince** [comment]
@alee8888 going to test this for you/Chema. This pull is really just to build a bundle for me :)

> hi Jason!
we’ve been working on https://issues.liferay.com/browse/LPS-79566 this week
I’ve just sent it to Eudaldo for review
https://github.com/ealonso/liferay-portal/pull/1689
GitHub
LPS-79566 Turns generic portlet messages into toast notifications by jbalsas · Pull Request #1689 · ealonso/liferay-portal
Chema Balsas [7:32 AM]
screen shot 2018-05-16 at 16 31 12
> Chema Balsas [7:32 AM]
screen shot 2018-05-16 at 16 31 25
> Chema Balsas [7:33 AM]
this is the end result… generic messages become toast notifications
and specific portlet messages stay inline within the portlet body
I expect this to break functional tests… could you guys put someone to assess this impact as soon as possible so we can come up with a strategy to land this as soon as we can?
I’d love to have this in before the end of the week, so we won’t be making any more UI changes after that

**Comment by brianchiu** [comment]
ci:test

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@brianchiu don't test this pull, the other one has more commits. Just reference the comment to know what's going on (Chema sent me all that info in slack)

**Comment by brianchiu** [comment]
ci:test

**Comment by jpince** [comment]
ci:stop

**Pull request closed without merging**
