### PR TITLE
LPS-82687 Inconsistent exporting of Personal Data

### PR DESCRIPTION
**Pull request by pei-jung**
Hi Albert,

Can you double check to make sure the fix works? Thanks\!

/cc @drewbrokke

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
@pei-jung John Co reviewed and tested. Everything looks good.

**Comment by pei-jung** [comment]
Thanks @alee8888 and @john-co! 👍

**Pull request closed without merging**
