### PR TITLE
master-qa-27219

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-27219

See 7.0.x changes [here](https://github.com/alee8888/liferay-portal/pull/301).
See accompanying build script [here](https://github.com/alee8888/liferay-portal/pull/298).

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:stop

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
SF for BLee:
1. Breakup addLDAPServer macro into smaller chunks, ie maybe one to navigate, one that adds, and one that tests the connection.
2. Consider making the LDAP server name a variable?

**Comment by alee8888** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alee8888** [comment]
SF for BLee
1. Broke out editing the LDAP server in testLDAPConnection into it's own macro.
2. Moved LDAP navigation from PortalSettings to PortalSettingsNavigator.

**Comment by alee8888** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/42604
https://github.com/brianchandotcom/liferay-portal/pull/42606

**Pull request closed without merging**
